/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/appointments': RouteRecordInfo<
      '/appointments',
      '/appointments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth': RouteRecordInfo<
      '/auth',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/credentials': RouteRecordInfo<
      '/credentials',
      '/credentials',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/patients': RouteRecordInfo<
      '/patients',
      '/patients',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/registrations/exams': RouteRecordInfo<
      '/registrations/exams',
      '/registrations/exams',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/registrations/procedures': RouteRecordInfo<
      '/registrations/procedures',
      '/registrations/procedures',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/registrations/professionals': RouteRecordInfo<
      '/registrations/professionals',
      '/registrations/professionals',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/appointments.vue': {
      routes:
        | '/appointments'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth.vue': {
      routes:
        | '/auth'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/credentials.vue': {
      routes:
        | '/credentials'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/patients.vue': {
      routes:
        | '/patients'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/registrations/exams.vue': {
      routes:
        | '/registrations/exams'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/registrations/procedures.vue': {
      routes:
        | '/registrations/procedures'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/registrations/professionals.vue': {
      routes:
        | '/registrations/professionals'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
